dist: trusty
sudo: required
language: generic

services:
 - docker

cache:
  directories:
    - ./node_modules

before_install:
 - docker build -t frontend .

before_script:
 - npm install -g --save @angular/cli
 - nvm install 14
 - nvm use 14
 - ng version

script:
 - npm run lint
 - npm run-script build 
 - docker run frontend npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox

