dist: trusty
sudo: required
language: generic

services:
 - docker

cache:
  directories:
    - ./node_modules

before_install:
 - npm install -g --save @angular/cli
 - docker build -t frontend .

before_script:

script:
 - ng lint
 - ng build --prod --base-href https://github.com/arditi1997/e-commerce-frontend
 - docker run frontend npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox

