dist: trusty
sudo: required
language: generic

services:
 - docker

cache:
  directories:
    - ./node_modules

before_install:
 - docker build -t frontend .

before_script:
 - rm -rf node_modules
 - npm cache clean -f 
 - nvm install 10
 - nvm install 12
 - nvm use 10
 - npm install -g --save @angular/cli@latest
 - npm link @angular/cli@latest
 - ng version

script:
 - ng lint
 - ng build --prod --base-href https://github.com/arditi1997/e-commerce-frontend
 - docker run frontend npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox

