dist: trusty
sudo: required
language: generic

services:
 - docker

cache:
  directories:
    - ./node_modules

before_install:
 - docker build -t frontend .

before_script:
 - nvm install 14
 - nvm use 14
 - npm install -g --save @angular/cli@13.1.3
 - npm link @angular/cli@13.1.3
 - npm i @angular-devkit/build-angular
 - npm i @angular-eslint/builder
 - ng version

script:
 - docker run -e CI=true frontend npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox

deploy:
    provider: elasticbeanstalk
    region: 'us-east-1'
    app: 'Ecommerce'
    env: 'Ecommerce-env'
    bucket_name: 'elasticbeanstalk-us-west-2-300168838125'
    bucket_path: 'Ecommerce'
    on:
      branch: main
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    skip_cleanup: true
