dist: trusty
sudo: required
language: generic

services:
 - docker

cache:
  directories:
    - ./node_modules

before_install:
 - docker build -t frontend .

script:
 - docker run frontend npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox