dist: trusty
sudo: required
language: generic

services:
 - docker

cache:
  directories:
    - ./node_modules

before_install:
 - docker build -t frontend .

before_script:
 - nvm install 14
 - nvm use 14
 - npm install -g --save @angular/cli@13.1.3
 - npm link @angular/cli@13.1.3
 - npm i @angular-devkit/build-angular
 - npm i @angular-eslint/builder
 - ng version

script:
 - ng lint
 - ng build --prod --base-href https://github.com/arditi1997/e-commerce-frontend
 - docker run frontend npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
