version: '3.3'
services:
  frontend-service:
    image: frontend50
    container_name: frontend50
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    expose:
      - 4200
    ports: 
        - '4200:4200' # Port mapping



