version: '3'
services:
 frontend-service:
    image: frontend
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    command: ['npm', 'run', 'start']
    ports:
      - "8080:8080"








